<?xml version="1.0" encoding="UTF-8" standalone="no"?>
 <wsdl:definitions name="@@infoNome@@"
     xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
     xmlns:tefh="http://telefonica.br/Common/TEFHeader/v1"
     xmlns:etrace="http://telefonica.br/Common/ErrorTrace/v1"
     targetNamespace="http://telefonica.br/@@infoTAM@@@@infoNome@@/v1"
     xmlns:tns="http://telefonica.br/@@infoTAM@@@@infoNome@@/v1"
     xmlns:types="http://telefonica.br/@@infoTAM@@@@infoNome@@/v1/types"
	 xmlns:fault="http://telefonica.br/Common/Fault/v1">
<wsdl:documentation >
     -WS - I Basic Profile 1.2 - Compliance
     - Namespace definido com base no TAM Framework 14.5
     - Níveis TAM: @@infoTAM@@
</wsdl:documentation >
	<wsp:Policy wsu:Id="custom_policy"  
				xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                xmlns="http://schemas.xmlsoap.org/ws/2004/09/policy" 
				xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" 
				xmlns:wssp="http://www.bea.com/wls90/security/policy" 
				xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
		<wsdl:documentation>
			Custom Policy Definition
		</wsdl:documentation>
		<orasp:customAssertionTelefonica xmlns:orasp="http://schemas.oracle.com/ws/2006/01/securitypolicy"/>
	</wsp:Policy>
	<wsdl:types>
		<xsd:schema>
@@Imports@@
			<xsd:import
					namespace="http://telefonica.br/Common/TEFHeader/v1"
					schemaLocation="@@LevelFromRoot@@common/types/TEFHeader.xsd"/>
		
			<xsd:import
					namespace="http://telefonica.br/Common/ErrorTrace/v1" 
					schemaLocation="@@LevelFromRoot@@common/types/ErrorTrace.xsd"/>
					
			<xsd:import
				namespace="http://telefonica.br/Common/Fault/v1"
				schemaLocation="@@LevelFromRoot@@common/types/FaultV1.xsd"/>
					
		</xsd:schema>
	</wsdl:types>
		 <wsdl:message name="InputValidationFaultMessage">
				<wsdl:documentation>
					Fault lançada quando a mensagem de entrada (input) for inválida.
				</wsdl:documentation>
				<wsdl:part name="InputValidationFault" element="fault:InputValidationFault"/>
			</wsdl:message>
				
				<wsdl:message name="MandatoryParameterMissingFaultMessage">
				<wsdl:documentation>
					Fault lançada quando elementos obrigatórios não estão presentes na mensagem.
				</wsdl:documentation>
				<wsdl:part name="MandatoryParameterMissingFault" element="fault:MandatoryParameterMissingFault"/>
			</wsdl:message>
			
			<wsdl:message name="GeneralFaultMessage">
				<wsdl:documentation>
					Fault lançada quando o erro não puder se mapeado para nenhuma outra falha especializada.
				</wsdl:documentation>
				<wsdl:part name="GeneralFault" element="fault:GeneralFault"/>
			</wsdl:message>
@@Messages@@
 	<wsdl:portType name="@@infoNome@@PortType" >
@@Operations@@
 	</wsdl:portType>
	<wsdl:binding name="@@infoNome@@SOAP" type="tns:@@infoNome@@PortType">
		<wsp:PolicyReference URI="#custom_policy" wsdl:required="false" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"/>  
		<soap11:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
@@BindingOperations@@
	</wsdl:binding>
	<wsdl:service name="@@infoNome@@">
		<wsdl:port binding="tns:@@infoNome@@SOAP" name="@@infoNome@@PORT">
			<soap11:address location="http://host:port/@@infoNome@@"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>

